### ISSUE TITLE
This is not working for akamai2.x

### ISSUE THREAD

**Issue by happybeo** [zedd3v/abck-dev#3]
hi, this parser is not working for akamai2.x.
In addition, I have a project that needs to solve some technical problems of Akamai sensor data. Could you please provide some help? I can pay for the technical service fee or a fixed share of the follow-up project as a thank you. Either way, I hope you can contact my discord:Micheal#2045

**Comment by zedd3v** [comment]
Which part isnt working? I just tested both parser and deobfuscator and they both work fine. Please provide an example

![Deobfuscator](https://user-images.githubusercontent.com/43217974/164210611-fea17f1c-822a-4799-b2b7-9349381c2f83.png)

![Parser](https://user-images.githubusercontent.com/43217974/164210766-da3d909c-a0e3-4893-b273-b390b47f93b3.png)

**Comment by happybeo** [comment]
Can you add my discord, I have some questions I would like to discuss with you. My discord: Micheal#2045
