### ISSUE TITLE
Partially working for v2.x

### ISSUE THREAD

**Issue by zenichanin** [zedd3v/abck-dev#4]
The deobfuscator only partially works for v2.x.  It does not deobfuscate the entire string completely.

Screenshot attached.

I can send you more info if needed, message me on discord (`KingZen#7609`).

![deobfuscator](https://user-images.githubusercontent.com/3399096/164469277-928d0ad9-801a-4ab9-b875-dce29dc94e30.png)

**Comment by zedd3v** [comment]
The parts necessary to make a full gen are there, your screenshot shows the irrelevant code

Take prior versions of akamai and compare with the deobfuscated part
